
# /api/* -> Netlify Function (서버사이드 프록시)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200
  force = true

# SPA 라우팅
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
