
# /api/* 요청을 EB 서버로 프록시
[[redirects]]
  from = "/api/*"
  to = "http://wewha.ap-northeast-2.elasticbeanstalk.com/api/:splat"
  status = 200
  force = true

# 리액트 라우터(SPA) 라우팅용
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
